version: "3"

services:
  catalog:
    image: ghcr.io/projectnessie/nessie
    container_name: catalog
    networks:
      iceberg-nessie-net:
    ports:
      - 19120:19120

  trino:
    image: trinodb/trino
    container_name: trino
    networks:
      iceberg-nessie-net:
    ports:
      - 8080:8080
    volumes:
      - "./example.properties:/etc/trino/catalog/example.properties"
      - "./post-init.sh:/tmp/post-init.sh"
      - "./post-init.full.sql:/tmp/post-init.sql"
    command:
      - "/tmp/post-init.sh"

  storage:
    image: minio/minio
    container_name: storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      iceberg-nessie-net:
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  # Minio Client Container
  mc:
    depends_on:
      - storage
    image: minio/mc
    container_name: mc
    networks:
      iceberg-nessie-net:
        aliases:
          - minio.storage
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://storage:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc mb minio/iceberg;
      /usr/bin/mc policy set public minio/warehouse;
      /usr/bin/mc policy set public minio/iceberg;
      tail -f /dev/null
      "
  # Ontop virtual knowledge graph engine
  ontop:
    image: ontop/ontop
    container_name: ontop
    networks:
      iceberg-nessie-net:
    environment:
      #      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/infraresilience.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/mapping.obda
      ONTOP_LENSES_FILE: /opt/ontop/input/lenses.json
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/trino_tpch.properties
#      ONTOP_PORTAL_FILE: /opt/ontop/input/infraresilience.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
      ONTOP_WAIT_FOR: "trino:8080"
#      ONTOP_WAIT_FOR: "iceberg-nessie-net:8080"
    volumes:
      - ./ontop/input:/opt/ontop/input
      - ./ontop/jdbc:/opt/ontop/jdbc
    ports:
      - "9090:8080"

networks:
  iceberg-nessie-net:
